// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe1h6kRVU3JVIIn_hg-nr89DrUDc_hJfA',
    appId: '1:769026409519:web:6c59bbfc3cdbae78bfb2da',
    messagingSenderId: '769026409519',
    projectId: 'pokedex-c54b5',
    authDomain: 'pokedex-c54b5.firebaseapp.com',
    storageBucket: 'pokedex-c54b5.appspot.com',
    measurementId: 'G-H494BC1QFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt2WnY9LbZLH4412GjhOtxn-uttCWXksU',
    appId: '1:769026409519:android:7a52470cfcc72ae3bfb2da',
    messagingSenderId: '769026409519',
    projectId: 'pokedex-c54b5',
    storageBucket: 'pokedex-c54b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRi_kCdRB4IKrRwNQRHEXpL0EOwTgmdYQ',
    appId: '1:769026409519:ios:ada0de5f5c1849dbbfb2da',
    messagingSenderId: '769026409519',
    projectId: 'pokedex-c54b5',
    storageBucket: 'pokedex-c54b5.appspot.com',
    iosBundleId: 'com.pokedex.pokedex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRi_kCdRB4IKrRwNQRHEXpL0EOwTgmdYQ',
    appId: '1:769026409519:ios:f1fa0f983b78aaa5bfb2da',
    messagingSenderId: '769026409519',
    projectId: 'pokedex-c54b5',
    storageBucket: 'pokedex-c54b5.appspot.com',
    iosBundleId: 'com.pokedex.pokedex.RunnerTests',
  );
}
